#!/bin/bash

#Verifica a existência de uma nova atualização da JRE
#e a instala se necessário.

#Este script foi desenvolvido para ser invocado pelo cron.daily
#ou pelo Anacron

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

DATE=`/bin/date +%Y-%m-%d`
LOGFILE=/var/log/wrb-getjava-${DATE}.log

/usr/local/bin/wrb-getjava -n 2>&1  >>"${LOGFILE}"
